# Site settings
title: 나의 일상 블로그
description: 일상, 대학원, 기타 이야기를 기록하는 공간
author: devtinatina
email: leekh7624@korea.ac.kr

# Profile settings
bio: "내 꿈은 평범. 두루두루 잘 산다는 뜻. 그렇게 살고싶다."
profile_image: https://github.com/devtinatina.png

# Social links
social_links:
  github: devtinatina
  email: leekh7624@korea.ac.kr

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# GitHub Pages specific settings
url: "https://devtinatina.github.io"
baseurl: ""

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
